application: hacksc-todolist
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: /public/favicon.ico
  upload: favicon\.ico

- url: /public
  static_dir: public

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
